//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.18 at 07:36:10 PM BST 
//


package com.dlg.deop.artifacts.rtsMockResPackage;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rtsMockResPackage package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rtsMockResPackage
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link Response.Scores }
     * 
     */
    public Response.Scores createResponseScores() {
        return new Response.Scores();
    }

    /**
     * Create an instance of {@link Response.Metadata }
     * 
     */
    public Response.Metadata createResponseMetadata() {
        return new Response.Metadata();
    }

    /**
     * Create an instance of {@link Response.AggregateScore }
     * 
     */
    public Response.AggregateScore createResponseAggregateScore() {
        return new Response.AggregateScore();
    }

    /**
     * Create an instance of {@link Response.Scores.Score }
     * 
     */
    public Response.Scores.Score createResponseScoresScore() {
        return new Response.Scores.Score();
    }

}
