//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.18 at 07:36:10 PM BST 
//


package rtsMockResPackage;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Metadata">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DocumentIdentifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AggregateScore">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DocumentScoreValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="DocumentRiskRating" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="NetworkScoreValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="NetworkRiskRating" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Scores">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Score" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metadata",
    "aggregateScore",
    "scores"
})
@XmlRootElement(name = "Response")
public class Response {

    @XmlElement(name = "Metadata", required = true)
    protected Response.Metadata metadata;
    @XmlElement(name = "AggregateScore", required = true)
    protected Response.AggregateScore aggregateScore;
    @XmlElement(name = "Scores", required = true)
    protected Response.Scores scores;

    /**
     * Gets the value of the metadata property.
     * 
     * @return
     *     possible object is
     *     {@link Response.Metadata }
     *     
     */
    public Response.Metadata getMetadata() {
        return metadata;
    }

    /**
     * Sets the value of the metadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response.Metadata }
     *     
     */
    public void setMetadata(Response.Metadata value) {
        this.metadata = value;
    }

    /**
     * Gets the value of the aggregateScore property.
     * 
     * @return
     *     possible object is
     *     {@link Response.AggregateScore }
     *     
     */
    public Response.AggregateScore getAggregateScore() {
        return aggregateScore;
    }

    /**
     * Sets the value of the aggregateScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response.AggregateScore }
     *     
     */
    public void setAggregateScore(Response.AggregateScore value) {
        this.aggregateScore = value;
    }

    /**
     * Gets the value of the scores property.
     * 
     * @return
     *     possible object is
     *     {@link Response.Scores }
     *     
     */
    public Response.Scores getScores() {
        return scores;
    }

    /**
     * Sets the value of the scores property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response.Scores }
     *     
     */
    public void setScores(Response.Scores value) {
        this.scores = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DocumentScoreValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="DocumentRiskRating" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="NetworkScoreValue" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="NetworkRiskRating" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "documentScoreValue",
        "documentRiskRating",
        "networkScoreValue",
        "networkRiskRating"
    })
    public static class AggregateScore {

        @XmlElement(name = "DocumentScoreValue")
        protected float documentScoreValue;
        @XmlElement(name = "DocumentRiskRating")
        protected byte documentRiskRating;
        @XmlElement(name = "NetworkScoreValue")
        protected float networkScoreValue;
        @XmlElement(name = "NetworkRiskRating")
        protected byte networkRiskRating;

        /**
         * Gets the value of the documentScoreValue property.
         * 
         */
        public float getDocumentScoreValue() {
            return documentScoreValue;
        }

        /**
         * Sets the value of the documentScoreValue property.
         * 
         */
        public void setDocumentScoreValue(float value) {
            this.documentScoreValue = value;
        }

        /**
         * Gets the value of the documentRiskRating property.
         * 
         */
        public byte getDocumentRiskRating() {
            return documentRiskRating;
        }

        /**
         * Sets the value of the documentRiskRating property.
         * 
         */
        public void setDocumentRiskRating(byte value) {
            this.documentRiskRating = value;
        }

        /**
         * Gets the value of the networkScoreValue property.
         * 
         */
        public float getNetworkScoreValue() {
            return networkScoreValue;
        }

        /**
         * Sets the value of the networkScoreValue property.
         * 
         */
        public void setNetworkScoreValue(float value) {
            this.networkScoreValue = value;
        }

        /**
         * Gets the value of the networkRiskRating property.
         * 
         */
        public byte getNetworkRiskRating() {
            return networkRiskRating;
        }

        /**
         * Sets the value of the networkRiskRating property.
         * 
         */
        public void setNetworkRiskRating(byte value) {
            this.networkRiskRating = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DocumentIdentifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "documentIdentifier"
    })
    public static class Metadata {

        @XmlElement(name = "DocumentIdentifier")
        protected int documentIdentifier;

        /**
         * Gets the value of the documentIdentifier property.
         * 
         */
        public int getDocumentIdentifier() {
            return documentIdentifier;
        }

        /**
         * Sets the value of the documentIdentifier property.
         * 
         */
        public void setDocumentIdentifier(int value) {
            this.documentIdentifier = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Score" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "score"
    })
    public static class Scores {

        @XmlElement(name = "Score")
        protected List<Response.Scores.Score> score;

        /**
         * Gets the value of the score property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the score property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getScore().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Response.Scores.Score }
         * 
         * 
         */
        public List<Response.Scores.Score> getScore() {
            if (score == null) {
                score = new ArrayList<Response.Scores.Score>();
            }
            return this.score;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value",
            "description"
        })
        public static class Score {

            @XmlElement(name = "Value")
            protected float value;
            @XmlElement(name = "Description", required = true)
            protected String description;
            @XmlAttribute(name = "id")
            protected String id;

            /**
             * Gets the value of the value property.
             * 
             */
            public float getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(float value) {
                this.value = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

        }

    }

}
